### ISSUE TITLE
Hangs at "Shall I install hex?"

### ISSUE THREAD

**Issue by wende** [JakeBecker/ide-elixir#12]
Using Erlang 20, Elixir 1.6.0 both using kerl and kiex

<img width="460" alt="screen shot 2018-03-14 at 14 50 23" src="https://user-images.githubusercontent.com/4634386/37406284-15131c04-2797-11e8-9561-beb3cbd99b48.png">

**Comment by JakeBecker** [comment]
This appears to be a bug in Atom IDE's implementation of the language server protocol, specifically the `window/showMessageRequest` request. The notification should include "Yes" and "No" buttons you can click to continue. I filed an issue on `atom-languageclient`: https://github.com/atom/atom-languageclient/issues/196 .  I'll leave this issue open until this is fixed.

In the meantime, you can run `mix` from the CLI once, and it should prompt you to install Hex, and then you won't see this message next time you launch Atom. Alternatively, I highly recommend trying out the ElixirLS extension for VS Code, which is a much more mature LSP client and supports several features that Atom does not: https://github.com/JakeBecker/vscode-elixir-ls

**Comment by JakeBecker** [comment]
The issue's been fixed in `atom-languageclient` and I've published a new release with the updated dependency. Should be working now.
