### ISSUE TITLE
elixir 1.9 breaks ide-elixir

### ISSUE THREAD

**Issue by javobalazs** [JakeBecker/ide-elixir#19]
### Is this the right repo?

This has already been fixed in ElixirLS.

https://github.com/JakeBecker/elixir-ls/issues/155

I have ide-elixir 0.2.23 (latest).

### Symptom

Immediately after updating to 1.9 this appears in the Diagnostics window:

```bash
an exception was raised:
    ** (UndefinedFunctionError) function Mix.Dep.loaded/1 is undefined or private
        (mix) Mix.Dep.loaded([])
        (language_server) lib/language_server/build.ex:16: anonymous fn/2 in ElixirLS.LanguageServer.Build.build/3
        (stdlib) timer.erl:166: :timer.tc/1
        (language_server) lib/language_server/build.ex:13: anonymous fn/2 in ElixirLS.LanguageServer.Build.build/3
        (kernel) global.erl:425: :global.trans/4
```

Also, the PLT building isn't successful, but I reckon this is because the crash above.

**Comment by robmckinnon** [comment]
I have the same symtoms as described above when using `ide-elixir 0.2.23` with `Elixir 1.9.0`.

The [ElixirLS v0.2.25 release](https://github.com/JakeBecker/elixir-ls/releases/tag/v0.2.25) contains a fix for Elixir 1.9 compatibility.

**Comment by koichirose** [comment]
Same issue here, is there a way to update elixir-ls within ide-elixir?

edit: nevermind, I simply copied the files from elixir-ls 0.2.25 to my ~/.atom/packages/ide-elixir directory.

**Comment by javobalazs** [comment]
> edit: nevermind, I simply copied the files from elixir-ls 0.2.25 to my ~/.atom/packages/ide-elixir directory.

I did the same, I downloaded elixir-ls 0.2.25 and replaced `~/.atom/packages/ide-elixir/elixir-ls-release` with its contents. You have to set the `.bat` and `.sh` files executable (permissions: octal `775`).

It did work, but when I upgraded to elixir 1.9, the PLT building didn't get triggered, and the dialyzer warnings disappeared, so I basically lost one of the most important points for using ide-elixir.

Apparently, simply replacing ElixirLS 0.2.23 with 0.2.25 is not enough.

Further details:
```bash
$ uname -a
Linux bacer 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by javobalazs** [comment]
I've found a fork where ElixirLS 0.2.25 was already incorporated but the problem was the same, the PLT building didn't get triggered.

https://github.com/mjc/ide-elixir

**Comment by javobalazs** [comment]
I've just installed it, upgraded to elixir 1.9. The PLT building was okay, and the dialyzer_manifest got generated for the open project (only one) in .elixir_ls. I opened another project but the dialyzer_manifest just wouldn't get generated for that, and for any other project either. So there seem to be still an issue.
