### ISSUE TITLE
Elixir PLT Never Finishes Building

### ISSUE THREAD

**Issue by vforgione** [JakeBecker/ide-elixir#5]
I've been getting a massive string of recurring pop ups with the message `Building core Elixir PLT. This will take a few minutes.`. This has been happening for the last 2 days (since a fresh install on my system).

Ubuntu 17.10
Atom: 1.23.1 x64
Atom IDE UI: 0.7.0
IDE Elixir: 0.2.3
Erlang: 1:20.1
Elixir: 1.5.2

![plt](https://user-images.githubusercontent.com/4360430/34055227-e3f338dc-e193-11e7-92ec-82434607c8f1.png)

**Comment by libnine** [comment]
Having the same issue in vs code:

![untitled](https://user-images.githubusercontent.com/31510420/36222071-2047f3d4-118e-11e8-9ad0-d548116c54fc.png)

**Comment by OvermindDL1** [comment]
It finished for me, just took a veeeeeery long time (like an hour), but that's the nature of slow positive typers...  ^.^;

**Comment by JakeBecker** [comment]
Likely the same issue as here: https://github.com/JakeBecker/vscode-elixir-ls/issues/38

I've released an update that should fix it. Please re-open if it does not. Thanks!

**Comment by OvermindDL1** [comment]
I'm on linux for comparison.  ^.^

**Comment by hebertsouza87** [comment]
2 days here
