### ISSUE TITLE
Auto formatting

### ISSUE THREAD

**Issue by jackfranklin** [JakeBecker/ide-elixir#9]
Hey,

Just firstly wanted to say thanks for this plugin, it's been really great using it :)

I was wondering if you had any plans to integrate with the auto code formatter that was introduced in Elixir 1.6? :)

Thanks!

Jack

**Comment by JakeBecker** [comment]
Glad you like it :)

It does support code formatting if your Elixir version is 1.6. It's in the menu under `Edit > Text > Format code` and the hotkey is `Cmd + Shift + C` by default on a Mac.
